# ═══════════════════════════════════════════════════════════════════════════════
# @file config/ssh/config.d/90-fallback.conf
# @description SSH — public git hosts
# @since 1.0.0
# ═══════════════════════════════════════════════════════════════════════════════

Host gitlab.com
    HostName gitlab.com
    User git
    IdentityFile ~/.ssh/id_ed25519
    IdentityFile ~/.ssh/id_github_ed25519
    PreferredAuthentications publickey

Host bitbucket.org
    HostName bitbucket.org
    User git
    IdentityFile ~/.ssh/id_ed25519
    IdentityFile ~/.ssh/id_github_ed25519
    PreferredAuthentications publickey

Host codeberg.org
    HostName codeberg.org
    User git
    IdentityFile ~/.ssh/id_ed25519
    PreferredAuthentications publickey

Host sr.ht
    HostName sr.ht
    User git
    IdentityFile ~/.ssh/id_ed25519
    PreferredAuthentications publickey
