"""
@file generators/src/emitters/base.py
@description Abstract base class for shell-specific code emitters
@abstract class ShellEmitter
@since 1.0.0
@version 1.0.0
@see docs/SSOT.md
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from pathlib import Path

from ..models import (
    AliasDefinitions,
    EnvDefinitions,
    FunctionDefinitions,
    InitDefinitions,
    KeybindingDefinitions,
    PathDefinitions,
)


class ShellEmitter(ABC):
    """
    @abstract class ShellEmitter
    @description Base class for generating shell-specific code from SSOT models
    @since 1.0.0
    """

    def __init__(self, output_dir: Path) -> None:
        """
        @param output_dir Path to the shell's generated/ directory
        """
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    @property
    @abstractmethod
    def shell_name(self) -> str:
        """@return Shell name identifier (bash, zsh, fish, nushell)"""
        ...

    @property
    def header(self) -> str:
        """@return Standard generated file header"""
        return (
            f"# ═══════════════════════════════════════════════════════════════\n"
            f"# AUTO-GENERATED by dotfiles-gen — DO NOT EDIT\n"
            f"# Source: definitions/*.toml\n"
            f"# Shell: {self.shell_name}\n"
            f"# ═══════════════════════════════════════════════════════════════\n"
        )

    @abstractmethod
    def emit_aliases(self, definitions: AliasDefinitions) -> str:
        """
        @description Generate alias code for this shell
        @param definitions Parsed alias definitions
        @return Generated shell code as string
        """
        ...

    @abstractmethod
    def emit_functions(self, definitions: FunctionDefinitions) -> str:
        """
        @description Generate function code for this shell
        @param definitions Parsed function definitions
        @return Generated shell code as string
        """
        ...

    @abstractmethod
    def emit_env(self, definitions: EnvDefinitions) -> str:
        """
        @description Generate environment variable code for this shell
        @param definitions Parsed env definitions
        @return Generated shell code as string
        """
        ...

    @abstractmethod
    def emit_path(self, definitions: PathDefinitions) -> str:
        """
        @description Generate PATH manipulation code for this shell
        @param definitions Parsed path definitions
        @return Generated shell code as string
        """
        ...

    @abstractmethod
    def emit_keybindings(self, definitions: KeybindingDefinitions) -> str:
        """
        @description Generate keybinding code for this shell
        @param definitions Parsed keybinding definitions
        @return Generated shell code as string
        """
        ...

    def emit_init(self, definitions: InitDefinitions) -> str:
        """
        @description Generate tool initialization code for this shell, sorted by priority
        @param definitions Parsed init definitions
        @return Generated shell code as string
        """
        sorted_entries = sorted(definitions.init.items(), key=lambda x: x[1].priority)
        eager_lines: list[str] = []
        lazy_lines: list[str] = []

        for name, entry in sorted_entries:
            init_cmd = getattr(entry, self.shell_name, "")
            if not init_cmd:
                continue

            if entry.lazy and entry.lazy_triggers:
                lazy_lines.append(f"\n# [{entry.priority}] {name} — {entry.description} [LAZY]")
                lazy_lines.append(
                    self._wrap_lazy_init(entry.verify, init_cmd, name, entry.lazy_triggers)
                )
            else:
                eager_lines.append(f"\n# [{entry.priority}] {name} — {entry.description}")
                eager_lines.append(self._wrap_init_check(entry.verify, init_cmd))

        lines = []
        if eager_lines:
            lines.append("\n# ─── Eager init (loaded at shell startup) ───")
            lines.extend(eager_lines)
        if lazy_lines:
            lines.append("\n\n# ─── Lazy init (deferred until first use) ───")
            lines.extend(lazy_lines)

        return "\n".join(lines) + "\n"

    def _wrap_init_check(self, verify_cmd: str, init_cmd: str) -> str:
        """
        @description Wrap init command in availability check (shell-specific)
        @param verify_cmd Command name to check
        @param init_cmd Init command to execute if available
        @return Wrapped init code
        """
        return f"if command -v {verify_cmd} >/dev/null 2>&1; then\n    {init_cmd}\nfi"

    def _wrap_lazy_init(
        self, verify_cmd: str, init_cmd: str, name: str, triggers: list[str]
    ) -> str:
        """
        @description Generate lazy-loading wrapper that defers init until first trigger use
        @param verify_cmd Command to check availability
        @param init_cmd Real init command to run on first trigger
        @param name Tool name (used for internal function naming)
        @param triggers Commands that trigger lazy loading
        @return Lazy wrapper shell code
        """
        func_name = f"_dotfiles_lazy_{name}"
        unset_list = " ".join(triggers)
        lines = [
            f"if command -v {verify_cmd} >/dev/null 2>&1; then",
            f"    {func_name}() {{"
            f" unset -f {unset_list} {func_name} 2>/dev/null;"
            f" unalias {unset_list} 2>/dev/null;"
            f" {init_cmd}; }}",
        ]
        for trigger in triggers:
            lines.append(
                f'    unalias {trigger} 2>/dev/null; {trigger}() {{ {func_name}; {trigger} "$@"; }}'
            )
        lines.append("fi")
        return "\n".join(lines)

    def write(self, filename: str, content: str) -> Path:
        """
        @description Write generated content to a file in the output directory
        @param filename Output filename
        @param content Generated content
        @return Path to the written file
        """
        filepath = self.output_dir / filename
        filepath.write_text(self.header + "\n" + content)
        return filepath
