"""
@file generators/src/emitters/nushell.py
@description Nushell-specific code emitter
@class NushellEmitter
@extends ShellEmitter
@since 1.0.0
@version 1.0.0
"""

from __future__ import annotations

from ..models import (
    AliasDefinitions,
    EnvDefinitions,
    FunctionDefinitions,
    KeybindingDefinitions,
    PathDefinitions,
)
from .base import ShellEmitter


class NushellEmitter(ShellEmitter):
    """
    @class NushellEmitter
    @extends ShellEmitter
    @description Generates Nushell-compatible code from SSOT definitions
    @since 1.0.0
    """

    @property
    def shell_name(self) -> str:
        return "nushell"

    @property
    def header(self) -> str:
        return (
            f"# ═══════════════════════════════════════════════════════════════\n"
            f"# AUTO-GENERATED by dotfiles-gen — DO NOT EDIT\n"
            f"# Source: definitions/*.toml\n"
            f"# Shell: {self.shell_name}\n"
            f"# ═══════════════════════════════════════════════════════════════\n"
        )

    def emit_aliases(self, definitions: AliasDefinitions) -> str:
        """Emit nushell aliases. Simple aliases use `alias`, ones with flags use `def`."""
        lines: list[str] = []
        for group_name, aliases in definitions.aliases.items():
            lines.append(f"\n# --- {group_name} ---")
            for name, alias in aliases.items():
                if name.startswith(".") or name == "-" or name == "~":
                    continue
                cmd = alias.command
                # Convert shell || to nushell try/catch
                import re

                cmd = re.sub(r"(.+?) \|\| (.+)", r"try { \1 } catch { \2 }", cmd)
                # Aliases containing flags/options need `def` for proper parsing
                has_flags = any(
                    token.startswith("-") or token.startswith("--") or "|" in cmd or ";" in cmd
                    for token in cmd.split()
                )
                if has_flags:
                    line = f"def --wrapped {name} [...rest] {{ {cmd} ...$rest }}"
                else:
                    line = f"alias {name} = {cmd}"
                if alias.requires:
                    lines.append(f"if (which {alias.requires} | is-not-empty) {{")
                    lines.append(f"    {line}")
                    lines.append("}")
                else:
                    lines.append(line)
        return "\n".join(lines) + "\n"

    def emit_functions(self, definitions: FunctionDefinitions) -> str:
        lines: list[str] = []
        for name, func in definitions.functions.items():
            lines.append(f"\n# {func.description}")
            body = func.body.strip()
            nushell_body = self._posix_to_nushell(body, name)
            if nushell_body is not None:
                lines.append(f"def {name} [...args] {{")
                for body_line in nushell_body.splitlines():
                    stripped = body_line.strip()
                    if stripped:
                        lines.append(f"    {stripped}")
                lines.append("}")
            else:
                lines.append(f"# {name}: skipped (uses unsupported construct like eval)")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _posix_to_nushell(body: str, name: str = "") -> str | None:
        """
        @description POSIX -> Nushell syntax conversion
        @param body POSIX shell function body
        @param name Function name (for unsupported-feature warnings)
        @return Nushell-compatible function body, or None if unsupported
        """
        import re

        result = body.strip()

        # Guard: functions Nushell cannot handle
        if re.search(r"\beval\b", result):
            return None

        # Variable substitutions
        result = re.sub(r"\$\{1:-([^}]*)\}", r'($args | first | default "\1")', result)
        result = re.sub(r"\$\{2:-([^}]*)\}", r'(try { $args | get 1 } catch { "\1" })', result)
        result = re.sub(r"\$@", "$args", result)
        result = re.sub(r"\$2", "($args | get 1)", result)
        result = re.sub(r"\$1", "($args | first)", result)

        # local -> let / mut
        result = re.sub(r"\blocal\s+(\w+)=(.*)", r"let \1 = \2", result)
        result = re.sub(r"\blocal\s+(\w+)", r"mut \1", result)

        # export -> $env. prefix
        result = re.sub(r"\bexport\s+(\w+)=(.*)", r"$env.\1 = \2", result)

        # [[ ... ]]; then -> if ( ... ) {
        result = re.sub(r"\[\[\s*(.+?)\s*\]\]\s*;\s*then", r"if (\1) {", result)
        result = re.sub(
            r"\[\[\s*!\s+-\s*(\w+)\s+(\S+)\s*\]\]",
            r"(not (\2 | path exists))",
            result,
        )
        result = re.sub(r"\[\[\s*-\s*(\w+)\s+(\S+)\s*\]\]", r"(\2 | path exists)", result)
        result = re.sub(r'\[\[\s*-n\s+"\$(.+?)"', r"($1 != null", result)
        result = re.sub(r'\[\[\s*-z\s+"\$(.+?)"\s*\]\]', r"($1 == null)", result)

        # fi -> } (protect elif first)
        result = re.sub(r"\belif\b", "__ELIF_PROTECT__", result)
        result = re.sub(r"\bfi\b", "}", result)
        result = re.sub(r"__ELIF_PROTECT__", "} else if", result)

        # case -> match
        result = re.sub(r'\bcase\s+"\$\(.+?\)\"\s+in\b', r"match ($args | first) {", result)
        result = re.sub(
            r"^(\s*)\*:([^:]*):\*\)\s*;;",
            r"\1$_\' => { null }",
            result,
            flags=re.MULTILINE,
        )
        result = re.sub(
            r"^(\s*)(\S+)\)\s*(.*?)\s*;;",
            r"\1\2 => { \3 },",
            result,
            flags=re.MULTILINE,
        )
        result = re.sub(
            r"^(\s*)\*\)\s*(.*?)\s*;;",
            r"\1_ => { \2 },",
            result,
            flags=re.MULTILINE,
        )
        result = re.sub(r"\besac\b", "}", result)

        # $() command substitution -> ( | str trim)
        result = re.sub(r"\$\((.+?)\)", r"(\1 | str trim)", result)

        # && -> ;  (nushell runs sequentially by default)
        result = re.sub(r"\s*&&\s*", "; ", result)

        # for ((i=0; i<n; i++)) -> for i in 0..<n
        result = re.sub(
            r"for\s*\(\(\s*(\w+)\s*=\s*(\d+)\s*;\s*\1\s*<\s*(\w+)\s*;\s*\1\+\+\s*\)\)",
            r"for \1 in \2..<\3",
            result,
        )

        # done -> nothing (nushell uses braces)
        result = re.sub(r"\bdone\b", "", result)

        # return 1 -> error make
        result = re.sub(r"\breturn\s+1\b", 'error make {msg: "operation failed"}', result)
        result = re.sub(r"\breturn\s+0\b", "return", result)

        # Clean up double spaces / trailing semicolons
        result = re.sub(r"  +", " ", result)
        result = re.sub(r";\s*;", ";", result)

        return result

    def emit_env(self, definitions: EnvDefinitions) -> str:
        lines: list[str] = []
        for group_name, env_vars in definitions.env.items():
            lines.append(f"\n# --- {group_name} ---")
            for name, var in env_vars.items():
                value = var.value
                if value.startswith("$(") or value.startswith("`"):
                    lines.append(f"# {name} = (dynamic, requires shell evaluation)")
                    continue
                value = value.replace("$HOME", "($env.HOME)")
                value = value.replace("$XDG_CONFIG_HOME", "($env.XDG_CONFIG_HOME)")
                value = value.replace("$XDG_CACHE_HOME", "($env.XDG_CACHE_HOME)")
                lines.append(f'$env.{name} = "{value}"')
        return "\n".join(lines) + "\n"

    def emit_path(self, definitions: PathDefinitions) -> str:
        lines: list[str] = ["\n# --- PATH construction ---"]
        lines.append("$env.PATH = ($env.PATH | split row (char esep))")
        for entry in definitions.path:
            path_val = entry.path.replace("$HOME", "($env.HOME)")
            path_val = path_val.replace("$GOPATH", "($env.GOPATH? | default '')")
            path_val = path_val.replace("$CARGO_HOME", "($env.CARGO_HOME? | default '')")
            if entry.condition:
                cond_path = entry.condition.replace("$HOME", "($env.HOME)")
                cond_path = cond_path.replace("$GOPATH", "($env.GOPATH? | default '')")
                cond_path = cond_path.replace("$CARGO_HOME", "($env.CARGO_HOME? | default '')")
                if entry.prepend:
                    lines.append(
                        f'if ("{cond_path}" | path exists) {{ '
                        f'$env.PATH = ("{path_val}" | prepend $env.PATH) }}'
                    )
                else:
                    lines.append(
                        f'if ("{cond_path}" | path exists) {{ '
                        f'$env.PATH = ($env.PATH | append "{path_val}") }}'
                    )
            else:
                if entry.prepend:
                    lines.append(f'$env.PATH = ("{path_val}" | prepend $env.PATH)')
                else:
                    lines.append(f'$env.PATH = ($env.PATH | append "{path_val}")')
        return "\n".join(lines) + "\n"

    def emit_keybindings(self, definitions: KeybindingDefinitions) -> str:
        lines: list[str] = ["\n# --- Keybindings ---"]
        lines.append("# Nushell keybindings are configured in config.nu $env.config.keybindings")
        lines.append("# See: https://www.nushell.sh/book/line_editor.html")
        return "\n".join(lines) + "\n"
